export const GET_ALL_SIMS = 'GET_ALL_SIMS';
export const GET_SIMS_PAGING = 'GET_SIMS_PAGING';
export const CHANGE_LOADING_STATUS = 'CHANGE_LOADING_STATUS';
export const GET_ALL_TELCOS = 'GET_ALL_TELCOS';
